### ALPHAVANTAGE
https://www.alphavantage.co/documentation/ <br>
<p> You will need to install AV Python Wrapper :</p>
https://github.com/RomelTorres/alpha_vantage
<br> 
<p> Data only in JSON output </p> 
<p> Ticker symbol may differ from what is available on Yahoo Finance </p>

In [9]:
YOUR_API_KEY_DIR = "C:\\Users\\Gigabyte\\Desktop\\quant-trading-python-bot\\AlphaVantage_API.txt"

In [10]:
# importing libraries
from alpha_vantage.timeseries import TimeSeries
import pandas as pd

In [15]:
#extracting data for single ticker
ts = TimeSeries(key= open(YOUR_API_KEY_DIR, 'r').read(), output_format='pandas')
data = ts.get_daily(symbol='EURUSD', outputsize='full')[0]
data.columns = ["open", "high", "low", "close", "volume"]

In [16]:
data

              open    high     low   close  volume
date
2020-05-06  1.0797  1.0797  1.0797  1.0797     0.0
2020-05-05  1.0841  1.0841  1.0841  1.0841     0.0
2020-05-04  1.0917  1.0917  1.0917  1.0917     0.0
2020-05-01  1.1007  1.1007  1.1007  1.1007     0.0
2020-04-30  1.0954  1.0954  1.0954  1.0954     0.0
...            ...     ...     ...     ...     ...
2000-05-12  0.9063  0.9063  0.9063  0.9063     0.0
2000-05-11  0.9034  0.9034  0.9034  0.9034     0.0
2000-05-10  0.9114  0.9114  0.9114  0.9114     0.0
2000-05-09  0.9023  0.9023  0.9023  0.9023     0.0
2000-05-08  0.8939  0.8939  0.8939  0.8939     0.0

[5058 rows x 5 columns]

In [24]:
# extracting stock data (intraday)

import time # used to override 5 api calls on AlphaVantage

all_tickers = ['AAPL', 'MSFT', 'CSCO', 'AMZN', 'GOOG', 'FB']
close_prices = pd.DataFrame()
api_call_count = 0

for ticker in all_tickers:
    starttime= time.time() #capture system time
    ts = TimeSeries(key=open(YOUR_API_KEY_DIR, 'r').read(), output_format = 'pandas')
    
    data = ts.get_intraday(symbol=ticker, interval ='1min', outputsize ='compact')[0]
    # get_intraday , interval of 1 min , output full 
    api_call_count +=1
    
    data.columns = ['open', 'high','low', 'close', 'volume']
    close_prices[ticker] = data['close']
    
    if api_call_count == 5:
        api_call_count = 0
        time.sleep(60 - (time.time()-starttime)) # sleep for 60 - time taken to get API query

In [26]:
close_prices.head()

,AAPL,MSFT,CSCO,AMZN,GOOG,FB
date,,,,,,
2020-05-07 16:00:00,303.7500,183.6078,41.380,2367.6101,1373.1500,211.3000
2020-05-07 15:59:00,303.5900,183.3800,41.310,2362.8149,1370.9301,211.1200
2020-05-07 15:58:00,303.3900,183.3600,41.300,2361.8450,1369.6200,210.9550
2020-05-07 15:57:00,303.3700,183.3909,41.310,2362.9500,1370.6400,210.9322
2020-05-07 15:56:00,303.2299,183.3150,41.335,2362.5701,1370.7000,210.8850

### Hmm.. Maybe we want the latest dates to be at the end of our dataframe instead..

In [ ]:
# extracting stock data (intraday)

import time # used to override 5 api calls on AlphaVantage

all_tickers = ['AAPL', 'MSFT', 'CSCO', 'AMZN', 'GOOG', 'FB']
close_prices = pd.DataFrame()
api_call_count = 0

for ticker in all_tickers:
    starttime= time.time() #capture system time
    ts = TimeSeries(key=open(YOUR_API_KEY_DIR, 'r').read(), output_format = 'pandas')
    
    data = ts.get_intraday(symbol=ticker, interval ='1min', outputsize ='compact')[0]
    # get_intraday , interval of 1 min , output full 
    api_call_count +=1
    
    data.columns = ['open', 'high','low', 'close', 'volume']
    
    # reverse order, will be important for strategies
    data = data.iloc[::-1]
    
    close_prices[ticker] = data['close']
    
    if api_call_count == 5:
        api_call_count = 0
        time.sleep(60 - (time.time()-starttime)) # sleep for 60 - time taken to get API query